#!/bin/bash

source orkhideya-root
ork_include if

_interface="$1"
! if_interface_exists "$_interface" && exit 1
! if_interface_down "$_interface" && exit 2
! brctl delbr "$_interface" && exit 3

exit 0
